version: '3.9'
services:

  mysql:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'keycloak'
      MYSQL_USER: 'keycloak'
      MYSQL_PASSWORD: 'keycloak'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -P 3306 -proot | grep 'mysqld is alive' || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 10
    networks:
      migration-keycloak-and-mysql-network:
        ipv4_address: 192.168.1.2

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    user: root
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: "mysql"
      KC_DB_URL: 'jdbc:mysql://192.168.1.2:3306/keycloak'
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_Hostname: localhost
      KC_HTTPS_KEY_STORE_PASSWORD: secret
    entrypoint: /bin/bash
    command: -c "cd /opt/keycloak/conf && keytool -genkeypair -alias localhost -keyalg RSA -keysize 2048 -validity 365 -keystore server.keystore -dname 'cn=Server Administrator,o=Acme,c=GB' -keypass secret -storepass secret && cd ../bin/ && ./kc.sh show-config && ./kc.sh start  --log-level=INFO --hostname=localhost"
    ports:
      - 8080:8080
      - 8443:8443
    restart: unless-stopped
    networks:
      migration-keycloak-and-mysql-network:
        ipv4_address: 192.168.1.3
    depends_on:
      mysql:
        condition: service_healthy

networks:
  migration-keycloak-and-mysql-network:
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1