server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankdb
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application-name: section16-auth-server
